obj-m += j36_mt6592_input.o
obj-m += j36_jd9365_panel.o
obj-m += j36_mt6592_audio.o
obj-m += j36_mt6592_usb_phy.o
obj-m += j36_mt6592_pmic.o
obj-m += j36_mt6592_backlight.o
obj-m += j36_fbmem.o

obj-m += j36_mt6592_wifi.o
j36_mt6592_wifi-y := j36_mt6592_wifi_main.o \
		     j36_mt6592_wifi_consys.o \
		     j36_mt6592_wifi_wmt.o \
		     j36_mt6592_wifi_hif.o \
		     j36_mt6592_wifi_cmd.o \
		     j36_mt6592_wifi_net.o
