/* SPDX-License-Identifier: MS-PL */
/*
 * Copyright (c) 2025-2026 the MixOS project and contributors
 * See device/j36-ultra/LICENSE for the licence text and what it covers.
 *
 * mixdash -- MixOS's dashboard for the J36 Ultra.
 *
 * WHY THIS EXISTS.  EmulationStation reaches the panel through SDL's KMSDRM
 * backend, which means EGL, which means GBM, which means Mesa's lima on a
 * Mali-450 -- five layers, and the screen stayed black with no error past
 * eglCreateContext.  This dashboard reaches the panel through none of them.
 *
 * WHY linuxfb AND NOT eglfs.  The LK has already lit this panel: it powered the
 * JD9365, pushed its 155 init records, turned the backlight on and left the display
 * controller scanning out of 0x82700000.  The device tree hands that buffer to
 * `simple-framebuffer', CONFIG_DRM_FBDEV_EMULATION is off so mediatek-drm never
 * takes /dev/fb0 away from it, and mediatek-drm programs no register until
 * somebody sets a mode.  So /dev/fb0 is a live 640x480 x8r8g8b8 window onto glass
 * that is already lit, and Qt's linuxfb plugin writes straight into it.  No EGL, no
 * GBM, no DRM master, no modeset, and nothing in the path that has not already been
 * proved by the kernel console drawing on this panel.
 *
 * WHY Qt AND NOT A HAND-WRITTEN COMPOSITOR.  Because the alternative was writing
 * one: rounded rectangles, gradients, alpha, a bitmap font, text metrics, elision,
 * a list view, a scroll bar.  Qt has all of that, Debian trixie packages it for
 * armhf, and `libqt5gui5t64' ships platforms/libqlinuxfb.so ready to use.  What is
 * ported from MVII's dashboard is its look -- theme.h is its palette, to the triple
 * -- and deliberately not its renderer.
 *
 * WHAT IT DOES NOT DO.  It does not draw with the GPU, so a child that sets its own
 * mode through /dev/dri/card0 takes the scanout with it and does not give it back.
 * That is a real limit and it is written down in launch() where it bites.
 *
 * WHY THERE IS A TRACE AND A WATCHDOG IN HERE.  Because the first boot of this
 * dashboard produced a photograph of a panel frozen mid-console with no dashboard on
 * it, and nothing whatever to say why -- and the reason it had nothing to say is this
 * program.  The bootargs are `console=ttyS0,115200n8 console=tty0': the last console=
 * is the one /dev/console becomes, so every journal+console line and every kernel
 * printk is drawn by fbcon on this panel.  Qt's linuxfb plugin, inside the
 * QApplication constructor, opens /dev/tty0 and sets KD_GRAPHICS -- and fbcon draws
 * nothing at all in KD_GRAPHICS.  So the instant the platform plugin initialises, the
 * only console this board has goes silent, keeping the last frame it drew, and every
 * message from that point on -- including the one line main() printed to say which
 * platform Qt had chosen -- exists only in a journal on an ext2 partition that the
 * machine flashing this card cannot even mount.
 *
 * Three things follow from that, and they are the difference between a photograph
 * that says something and one that does not:
 *
 *   - The mode switch is Qt's to make and now it is ours.  `nographicsmodeswitch'
 *     tells the plugin to leave the console alone; this file sets KD_GRAPHICS itself
 *     from the FIRST PAINT, when there is finally something better to show than
 *     kernel messages.  Fail before that and the console is still live to say so.
 *   - Every phase is announced before it is entered, line-buffered, so the last line
 *     on the glass names the phase that did not finish.
 *   - A SIGALRM deadline per phase, and a handler on every fatal signal, put the
 *     console back into KD_TEXT before the process leaves.  A dashboard that dies
 *     holding KD_GRAPHICS takes the board's only console with it.
 */
#include "dashboard.h"

/*
 * Generated by build-in-vm.sh next to the sources it hashes, and not committed, so a
 * tree built by hand with `qmake && make' has no such file.  __has_include is what
 * keeps that case building; the build then simply reports itself as unknown.
 */
#if defined(__has_include)
#  if __has_include("buildid.h")
#    include "buildid.h"
#  endif
#endif
#ifndef MIXDASH_BUILD_ID
#define MIXDASH_BUILD_ID "unknown"
#endif

#include <QApplication>
#include <QDir>
#include <QFileInfo>
#include <QFontDatabase>
#include <QScreen>
#include <QStringList>
#include <QTimer>

#include <errno.h>
#include <fcntl.h>
#include <linux/fb.h>
#include <linux/kd.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

namespace {

/* ── the trace, the tty and the watchdog ─────────────────────────────────────── */

/* Opened before Qt is, and kept open, because the SIGALRM and SIGSEGV handlers need
 * it and open() is not something to do from a signal handler. */
int g_ttyFd = -1;
/* True only when THIS process set KD_GRAPHICS.  If Qt set it -- an older unit file
 * without nographicsmodeswitch -- restoring it is Qt's business, not ours. */
volatile sig_atomic_t g_ownGraphics = 0;
/* Read by the signal handlers.  A literal in every case, so there is nothing to free
 * and nothing that can be half-written when a handler reads it. */
const char *volatile g_phase = "start";
struct timespec g_t0;
int g_deadline = 90;

double elapsed(void)
{
    struct timespec now;
    ::clock_gettime(CLOCK_MONOTONIC, &now);
    return double(now.tv_sec - g_t0.tv_sec) + double(now.tv_nsec - g_t0.tv_nsec) / 1e9;
}

/* write(2) in a loop and strlen: the only two things below that a signal handler is
 * allowed to reach for.  printf is not one of them -- it takes a lock the interrupted
 * code may already hold. */
void writeAll(int fd, const char *s)
{
    size_t left = ::strlen(s);
    while (left > 0) {
        const ssize_t n = ::write(fd, s, left);
        if (n <= 0)
            return;
        s += n;
        left -= size_t(n);
    }
}

void textMode(void)
{
    if (g_ttyFd >= 0 && g_ownGraphics) {
        ::ioctl(g_ttyFd, KDSETMODE, KD_TEXT);
        g_ownGraphics = 0;
    }
}

/*
 * Announce the phase, then give it a deadline.  Every checkpoint re-arms the alarm,
 * so what the watchdog measures is "this phase has taken too long", not "startup
 * has": a slow phase that finishes is not a stall.  90 s by default because this
 * board took 102 s to get through the kernel and fontconfig's first run on a cold
 * ext2 is minutes-capable; MIXDASH_DEADLINE=0 turns it off.
 */
void phase(const char *name)
{
    g_phase = name;
    ::printf("mixdash: [%7.2fs] %s\n", elapsed(), name);
    ::fflush(stdout);
    if (g_deadline > 0)
        ::alarm(unsigned(g_deadline));
}

void onStall(int)
{
    /* KD_TEXT FIRST.  Everything below it is written to a console that is not being
     * drawn until this ioctl lands. */
    textMode();
    writeAll(2, "\nmixdash: WATCHDOG -- phase \"");
    writeAll(2, g_phase);
    writeAll(2, "\" did not finish.  Exiting so the console comes back.\n");
    ::_exit(3);
}

void onFatal(int sig)
{
    textMode();
    writeAll(2, "\nmixdash: died in phase \"");
    writeAll(2, g_phase);
    writeAll(2, "\"\n");
    /* Re-raised with the default disposition so the kernel still reports the fault
     * and the exit status still says what happened.  systemd's Restart=on-failure
     * reads that status. */
    ::signal(sig, SIG_DFL);
    ::raise(sig);
}

void onTerm(int)
{
    textMode();
    writeAll(2, "\nmixdash: asked to stop; console back in text mode\n");
    ::_exit(0);
}

/*
 * The handover.  Called from the first paintEvent -- not before -- so that anything
 * that goes wrong on the way to a frame is still readable on the glass.
 */
void takeGraphicsMode(void)
{
    int mode = KD_TEXT;
    if (g_ttyFd < 0 || g_ownGraphics)
        return;
    if (::ioctl(g_ttyFd, KDGETMODE, &mode) == 0 && mode == KD_GRAPHICS)
        return;                 /* Qt's plugin already did it; leave it Qt's to undo */
    if (::ioctl(g_ttyFd, KDSETMODE, KD_GRAPHICS) == 0)
        g_ownGraphics = 1;
}

/*
 * WHICH BUILD IS ON THE GLASS.  This board is updated across two partitions by two
 * different means: the boot image -- kernel, initramfs, /init -- is dragged onto the
 * vfat BOOT partition, which is the only one a Mac can write, while this binary lives
 * under /opt/mixos on an ext2 partition that a Mac cannot even mount and gets there
 * either baked into the image or unpacked from sd-root.tar.gz by /init.  Either half
 * can therefore be a version behind the other with nothing to show it, and an old
 * dashboard failing in an old way is indistinguishable from a new one failing -- which
 * is exactly the hour that was lost to a boot whose artifacts predated the fix.
 *
 * So /init passes on the id the boot image was built with and this says whether the
 * binary agrees.  Both ids are the first twelve characters of a sha256 over the
 * dashboard's own sources, so "they agree" means the two halves came out of one build.
 */
void announceBuild(void)
{
    const QByteArray expect = qgetenv("MIXDASH_EXPECT");

    ::printf("mixdash: build %s\n", MIXDASH_BUILD_ID);
    if (expect.isEmpty()) {
        ::printf("mixdash: nothing said which build was expected -- either this was run "
                 "from a shell, or the boot image predates the check\n");
        return;
    }
    if (expect == MIXDASH_BUILD_ID) {
        ::printf("mixdash: the boot image expected %s, so both halves are this build\n",
                 expect.constData());
        return;
    }

    ::printf("mixdash: MISMATCH -- the boot image expected %s, this binary is %s.\n",
             expect.constData(), MIXDASH_BUILD_ID);
    ::printf("mixdash: one half of the card was not updated.  If the boot image is the\n"
             "         newer one, sd-root.tar.gz never unpacked onto the OS partition --\n"
             "         look further up for /init's \"stage:\" lines.  If this binary is\n"
             "         the newer one, the boot image on BOOT is stale: copy sd-boot/ over\n"
             "         again.  Whatever the trace below says, it is not about the sources\n"
             "         you last changed.\n");
}

/*
 * --probe runs before QApplication on purpose.  If the platform plugin is missing
 * or the framebuffer is not what the device tree said, this still answers, and its
 * answer is the first thing worth having from a boot that drew nothing.
 */
int probe(void)
{
    const int fd = ::open("/dev/fb0", O_RDONLY);
    if (fd < 0) {
        ::printf("mixdash: /dev/fb0 cannot be opened (%s)\n", ::strerror(errno));
        ::printf("mixdash: FB_SIMPLE should have bound the device tree's "
                 "simple-framebuffer node -- check dmesg for simple-framebuffer\n");
        return 1;
    }

    struct fb_var_screeninfo var;
    struct fb_fix_screeninfo fix;
    ::memset(&var, 0, sizeof(var));
    ::memset(&fix, 0, sizeof(fix));
    if (::ioctl(fd, FBIOGET_VSCREENINFO, &var) < 0
        || ::ioctl(fd, FBIOGET_FSCREENINFO, &fix) < 0) {
        ::printf("mixdash: /dev/fb0 opened but answered no geometry (%s)\n", ::strerror(errno));
        ::close(fd);
        return 1;
    }

    ::printf("mixdash: /dev/fb0 is \"%s\", %ux%u, %u bpp, stride %u, %u bytes mapped\n",
             fix.id, var.xres, var.yres, var.bits_per_pixel, fix.line_length, fix.smem_len);
    ::printf("mixdash: channels r%u@%u g%u@%u b%u@%u a%u@%u\n",
             var.red.length, var.red.offset, var.green.length, var.green.offset,
             var.blue.length, var.blue.offset, var.transp.length, var.transp.offset);

    /*
     * 32 bits per pixel is what the device tree's `x8r8g8b8' promises and what Qt's
     * raster engine can blit into without a conversion pass.  16 would still work
     * and would still be worth saying out loud.
     */
    if (var.bits_per_pixel != 32 && var.bits_per_pixel != 16)
        ::printf("mixdash: %u bpp is neither 16 nor 32; linuxfb will refuse it\n",
                 var.bits_per_pixel);

    ::close(fd);
    return 0;
}

/*
 * One font, found rather than assumed.  The payload's own copy comes first so the
 * dashboard looks the same on a card whose rootfs has no fonts at all; the rootfs
 * copies are the fallback, and if neither is there Qt falls back to whatever
 * fontconfig can find and the dashboard still draws.
 */
QString loadFont()
{
    QStringList files;
    const QDir payload("/opt/mixos/qt/fonts");
    if (payload.exists())
        for (const QString &f : payload.entryList(QStringList() << "*.ttf", QDir::Files, QDir::Name))
            files << payload.filePath(f);
    files << "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
          << "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
          << "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf";

    QString family;
    for (const QString &f : files) {
        if (!QFileInfo::exists(f))
            continue;
        const int id = QFontDatabase::addApplicationFont(f);
        if (id < 0)
            continue;
        const QStringList families = QFontDatabase::applicationFontFamilies(id);
        if (!families.isEmpty() && family.isEmpty())
            family = families.first();
    }
    return family;
}

/*
 * The platform spec, defaulted rather than demanded.  An explicit QT_QPA_PLATFORM
 * still wins -- that is how this binary runs under X or Wayland on a development
 * machine -- but `linuxfb' on its own is completed to
 * `linuxfb:nographicsmodeswitch', because the unit file that names it lives on the
 * BOOT partition and this binary lives on the OS partition, and the two are updated
 * by different means.  A card whose /init predates the option would otherwise put
 * the console back in KD_GRAPHICS at plugin init and take the panel with it.
 */
void defaultPlatform(void)
{
    QByteArray spec = qgetenv("QT_QPA_PLATFORM");
    if (spec.isEmpty())
        spec = "linuxfb";
    if (!spec.startsWith("linuxfb"))
        return;
    if (!spec.contains("graphicsmodeswitch"))
        spec += ":nographicsmodeswitch";
    qputenv("QT_QPA_PLATFORM", spec);
}

/*
 * QStandardPaths warns about XDG_RUNTIME_DIR before anything else this program does,
 * and it is right to: Qt puts its own sockets and lock files there.  systemd's
 * RuntimeDirectory= makes this directory, but the dashboard has to be runnable from a
 * shell too, so it is made here when nobody has made it.
 */
void defaultRuntimeDir(void)
{
    if (qEnvironmentVariableIsSet("XDG_RUNTIME_DIR"))
        return;
    if (::mkdir("/run/mixdash", 0700) == 0 || errno == EEXIST)
        qputenv("XDG_RUNTIME_DIR", "/run/mixdash");
}

} /* namespace */

int main(int argc, char **argv)
{
    bool once = false;
    bool windowed = false;
    bool qtInput = false;

    ::clock_gettime(CLOCK_MONOTONIC, &g_t0);
    /*
     * Line-buffered, and this is not cosmetic.  stdout under systemd is a pipe to the
     * journal, so libc block-buffers it: a checkpoint printed just before a hang sits
     * in a 4 KB buffer and is never seen, which is precisely what happened to the one
     * line this program used to print.  stderr is unbuffered already, which is the
     * only reason the QStandardPaths warning made it onto the glass.
     */
    ::setvbuf(stdout, NULL, _IOLBF, 0);

    for (int i = 1; i < argc; ++i) {
        const char *a = argv[i];
        if (!::strcmp(a, "--probe")) {
            announceBuild();
            return probe();
        }
        if (!::strcmp(a, "--once"))
            once = true;
        else if (!::strcmp(a, "--windowed"))
            windowed = true;
        else if (!::strcmp(a, "--qt-input"))
            qtInput = true;
        else if (!::strcmp(a, "--help") || !::strcmp(a, "-h")) {
            ::printf("mixdash -- the MixOS dashboard\n"
                     "  --probe      report /dev/fb0's geometry and exit\n"
                     "  --once       draw one screen, wait three seconds, exit 0\n"
                     "  --windowed   do not go fullscreen (for a development machine)\n"
                     "  --qt-input   let Qt read evdev instead of the built-in map\n"
                     "\n"
                     "MIXDASH_DEADLINE=<s>  watchdog per startup phase (0 off, 90 default)\n"
                     "MIXDASH_EXPECT=<id>   build the boot image expects; /init sets it\n"
                     "\n"
                     "This is build " MIXDASH_BUILD_ID ".\n");
            return 0;
        }
    }

    if (qEnvironmentVariableIsSet("MIXDASH_DEADLINE"))
        g_deadline = qEnvironmentVariableIntValue("MIXDASH_DEADLINE");

    /*
     * First, before the tty and before Qt.  If the two halves of the card disagree then
     * nothing below is evidence about the sources anybody last edited, and that has to
     * be the first line read rather than something inferred from the last.
     */
    announceBuild();

    /*
     * The tty before the framebuffer, and both before Qt.  O_RDWR because KDSETMODE
     * needs it; failure is not fatal and not even unusual -- run from ssh there is no
     * /dev/tty0 to open -- but on this board it is the console, and a dashboard that
     * cannot put it back into text mode is a dashboard that can silence the machine.
     */
    g_ttyFd = ::open("/dev/tty0", O_RDWR | O_CLOEXEC);
    if (g_ttyFd < 0)
        ::printf("mixdash: /dev/tty0 will not open (%s); the console mode is not ours\n",
                 ::strerror(errno));

    ::signal(SIGALRM, onStall);
    ::signal(SIGTERM, onTerm);
    ::signal(SIGINT, onTerm);
    ::signal(SIGHUP, onTerm);
    ::signal(SIGSEGV, onFatal);
    ::signal(SIGABRT, onFatal);
    ::signal(SIGBUS, onFatal);
    ::signal(SIGFPE, onFatal);
    ::signal(SIGILL, onFatal);
    ::atexit(textMode);

    /*
     * The framebuffer's own answer, every boot and not just under --probe.  Six lines,
     * and they are the six that decide whether anything after them can possibly draw.
     */
    phase("framebuffer");
    (void)probe();

    /*
     * Set before QApplication, because the platform plugin reads its environment
     * while it is being constructed.
     */
    defaultPlatform();
    defaultRuntimeDir();
    if (!qtInput && !qEnvironmentVariableIsSet("QT_QPA_FB_DISABLE_INPUT"))
        qputenv("QT_QPA_FB_DISABLE_INPUT", "1");
    ::printf("mixdash: QT_QPA_PLATFORM=%s\n", qgetenv("QT_QPA_PLATFORM").constData());

    phase("QApplication -- loads the platform plugin and opens /dev/fb0");
    QApplication app(argc, argv);
    app.setApplicationName("mixdash");
    app.setApplicationDisplayName("MixOS");
    app.setOverrideCursor(Qt::BlankCursor);

    /*
     * The platform and the geometry, HERE, and not at the end of startup where this
     * line used to be.  It is the answer to "did linuxfb bind", and a phase after it
     * that never returns must not be allowed to take the answer with it.
     */
    const QScreen *screen = QApplication::primaryScreen();
    ::printf("mixdash: %s on %s, %dx%d\n",
             QT_VERSION_STR,
             qPrintable(QApplication::platformName()),
             screen ? screen->geometry().width() : 0,
             screen ? screen->geometry().height() : 0);

    /*
     * Its own phase because it is the first plausible suspect for a startup that
     * reaches no frame: Qt5 on Debian links libfontconfig into QtGui, so this is
     * where fontconfig builds its cache if the rootfs has none -- a whole-system font
     * scan, on a 1.7 GHz A7, off an SD card.  QT_QPA_FONTDIR does not prevent it;
     * only QBasicFontDatabase reads that variable, and this build has fontconfig.
     */
    phase("fonts -- QFontDatabase, and fontconfig behind it");
    const QString family = loadFont();
    ::printf("mixdash: font \"%s\"\n",
             family.isEmpty() ? "fontconfig default" : qPrintable(family));
    QFont f = family.isEmpty() ? app.font() : QFont(family);
    f.setPixelSize(13);
    app.setFont(f);

    /*
     * Also its own phase, and for the same reason: the constructor builds four pages,
     * and one of them puts a QFileSystemModel on /run/j36/card -- a read-only mount of
     * a partition on the same SD card this program was loaded from.
     */
    phase("Dashboard -- four pages, the dock and the evdev map");
    Dashboard dash;

    /*
     * The console stops being drawn on when the dashboard first paints, and not one
     * moment sooner.  Failing before this point leaves every line above on the glass.
     */
    QObject::connect(&dash, &Dashboard::firstPainted, &app, []() {
        phase("first paint -- the console is now KD_GRAPHICS");
        takeGraphicsMode();
        /* Startup is over; a deadline from here would kill a working dashboard. */
        ::alarm(0);
        ::signal(SIGALRM, SIG_DFL);
    });

    phase("show -- fullscreen, and then the first frame");
    if (windowed) {
        dash.resize(640, 480);
        dash.show();
    } else {
        dash.showFullScreen();
    }

    if (once)
        QTimer::singleShot(3000, &app, []() { QApplication::quit(); });

    const int rc = app.exec();
    phase("exit");
    textMode();
    return rc;
}
