/* SPDX-License-Identifier: MPL-2.0 OR GPL-2.0-or-later */
/*
 * Copyright (c) 2025-2026 the MixOS project and contributors
 * See device/j36-ultra/LICENSE for the licence text and what it covers.
 *
 * mixdash -- MixOS's dashboard for the J36 Ultra.
 *
 * WHY THIS EXISTS.  A front end built on SDL reaches the panel through its KMSDRM
 * backend, which means EGL, which means GBM, which means Mesa's lima on a
 * Mali-450 -- five layers, and the screen stayed black with no error past
 * eglCreateContext.  This dashboard reaches the panel through none of them.
 *
 * WHY linuxfb AND NOT eglfs.  The LK has already lit this panel: it powered the
 * JD9365, pushed its 155 init records, turned the backlight on and left the display
 * controller scanning out of 0x82700000.  The device tree hands that buffer to
 * `simple-framebuffer', CONFIG_DRM_FBDEV_EMULATION is off so mediatek-drm never
 * takes /dev/fb0 away from it, and mediatek-drm programs no register until
 * somebody sets a mode.  So /dev/fb0 is a live 640x480 x8r8g8b8 window onto glass
 * that is already lit, and Qt's linuxfb plugin writes straight into it.  No EGL, no
 * GBM, no DRM master, no modeset, and nothing in the path that has not already been
 * proved by the kernel console drawing on this panel.
 *
 * WHY Qt AND NOT A HAND-WRITTEN COMPOSITOR.  Because the alternative was writing
 * one: rounded rectangles, gradients, alpha, a bitmap font, text metrics, elision,
 * a list view, a scroll bar.  Qt has all of that, Debian trixie packages it for
 * armhf, and `libqt5gui5t64' ships platforms/libqlinuxfb.so ready to use.  What is
 * ported from MVII's dashboard is its look -- theme.h is its palette, to the triple
 * -- and deliberately not its renderer.
 *
 * WHAT IT DOES NOT DO.  It does not draw with the GPU, so a child that sets its own
 * mode through /dev/dri/card0 takes the scanout with it and does not give it back.
 * That is a real limit and it is written down in launch() where it bites.
 *
 * WHY THERE IS A TRACE AND A WATCHDOG IN HERE.  Because the first boot of this
 * dashboard produced a photograph of a panel frozen mid-console with no dashboard on
 * it, and nothing whatever to say why -- and the reason it had nothing to say is this
 * program.  The bootargs are `console=ttyS0,115200n8 console=tty0': the last console=
 * is the one /dev/console becomes, so every journal+console line and every kernel
 * printk is drawn by fbcon on this panel.  Qt's linuxfb plugin, inside the
 * QApplication constructor, opens /dev/tty0 and sets KD_GRAPHICS -- and fbcon draws
 * nothing at all in KD_GRAPHICS.  So the instant the platform plugin initialises, the
 * only console this board has goes silent, keeping the last frame it drew, and every
 * message from that point on -- including the one line main() printed to say which
 * platform Qt had chosen -- exists only in a journal on an ext2 partition that the
 * machine flashing this card cannot even mount.
 *
 * Three things follow from that, and they are the difference between a photograph
 * that says something and one that does not:
 *
 *   - The mode switch is Qt's to make and now it is ours.  `nographicsmodeswitch'
 *     tells the plugin to leave the console alone; this file sets KD_GRAPHICS itself
 *     from the FIRST PAINT, when there is finally something better to show than
 *     kernel messages.  Fail before that and the console is still live to say so.
 *   - Every phase is announced before it is entered, line-buffered, so the last line
 *     on the glass names the phase that did not finish.
 *   - A SIGALRM deadline per phase, and a handler on every fatal signal, put the
 *     console back into KD_TEXT before the process leaves.  A dashboard that dies
 *     holding KD_GRAPHICS takes the board's only console with it.
 *
 * The trace itself moved to trace.cpp when a phase turned out not to be fine-grained
 * enough: `Dashboard dash;' is one statement and eleven objects, and naming the
 * statement named none of them.  It announces its own steps now.  alloc.cpp is the
 * other half of the same lesson -- std::bad_alloc says nothing about the size that
 * was asked for, and the size is the difference between "this board ran out of
 * memory" and "some length was computed as a negative number".  It also holds the
 * __cxa_throw hook, which is the only place a throw from inside Qt can be caught
 * standing on the frames that threw it.
 *
 * AND THE BUILD ID IS PRINTED AT EVERY FAILURE, not only at the top.  The first crash
 * report off this board was read for a day as evidence about code that was not on the
 * card: the line that would have said so was thirty lines above the crash on a screen
 * thirty lines tall.
 */
#include "console.h"
#include "dashboard.h"
#include "media.h"
#include "region.h"
#include "stringsdb.h"
#include "trace.h"
#include "volumes.h"

/*
 * Generated by build-in-vm.sh next to the sources it hashes, and not committed, so a
 * tree built by hand with `qmake && make' has no such file.  __has_include is what
 * keeps that case building; the build then simply reports itself as unknown.
 */
#if defined(__has_include)
#  if __has_include("buildid.h")
#    include "buildid.h"
#  endif
#endif
#ifndef MIXDASH_BUILD_ID
#define MIXDASH_BUILD_ID "unknown"
#endif

#include <QApplication>
#include <QDir>
#include <QFileInfo>
#include <QFontDatabase>
#include <QScreen>
#include <QStringList>
#include <QTimer>

#include <exception>

#include <errno.h>
#include <fcntl.h>
#include <linux/fb.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

namespace {

/* ── the trace and the watchdog ──────────────────────────────────────────────── */

/*
 * The tty and the console mode used to be two globals here.  They are console.cpp's
 * now, and console.h says why at length: a page that shells out waits for the child
 * with the event loop stopped, so the mode has to be re-takeable from somewhere
 * other than a timer in this file.
 *
 * What is left is where the stream goes once there is a dashboard to protect.
 * /run/j36 is the initramfs's own directory on the rootfs tmpfs, which is where
 * eglprobe.log and bootdev already are, and j36-logdump copies it into
 * BOOT:/mixos-log.txt so it comes off the board with everything else.
 */
const char kLogPath[] = "/run/j36/mixdash.log";

/*
 * MIXDASH_EXPECT, copied into a fixed buffer at startup.  It is read again at the
 * bottom of every failure path, and those run from signal handlers and from a
 * terminate handler, where a QByteArray is not something to be dereferencing.
 */
char g_expect[24];

/* Set by whichever path has already printed a full report, so the SIGABRT that follows
 * it does not print the same three things again.  Thirty lines is the whole panel. */
volatile sig_atomic_t g_reported = 0;

/*
 * WHY THE BUILD ID IS PRINTED AT THE FAILURE AND NOT ONLY AT THE TOP.  announceBuild
 * says all this in full on the first line of the run -- and on a 640x480 console that
 * is thirty lines above the crash, which is to say gone.  A photograph of the failure
 * is the only report this board can make, and a photograph that cannot say which build
 * it is of has cost this bring-up a day at a time: an old dashboard failing in an old
 * way is indistinguishable from a new one failing.  So the verdict is repeated where
 * the evidence is.
 */
void writeBuild(void)
{
    Trace::writeAll(2, "mixdash: this is build " MIXDASH_BUILD_ID);
    if (g_expect[0] != '\0' && ::strcmp(g_expect, MIXDASH_BUILD_ID) != 0) {
        Trace::writeAll(2, ", but the boot image expected ");
        Trace::writeAll(2, g_expect);
        Trace::writeAll(2, "\nmixdash: HALF THIS CARD IS STALE -- what failed above is not "
                           "the code you last changed");
    }
    Trace::writeAll(2, "\n");
}

/*
 * TELLING THE SPLASH TO GO, WHICH IS NOW THIS PROGRAM'S JOB AND NOT THE UNIT FILE'S.
 *
 * mixdash.service used to send "quit" from an ExecStartPre, a second before this
 * binary was even exec'd, and the unit said in so many words that a frozen splash was
 * the right thing to look at while Qt did its dynamic linking.  It is not, and the
 * board showed why twice over:
 *
 *   - mixsplash re-takes KD_GRAPHICS once a second for as long as it runs, and that
 *     is the ONLY thing holding the console off this panel -- systemd, agetty and
 *     vconsole-setup each reset the VT to KD_TEXT during that same stretch of the
 *     boot.  Kill the splash before the dashboard paints and the next reset wins, so
 *     fbcon starts drawing into the gap: the journal, the login banner and this
 *     program's own StandardOutput=journal+console startup trace, for the second or
 *     so it takes to reach a frame.  That is the "quick console text info just before
 *     the dashboard".
 *   - What is left on the glass in the meantime is one still frame, held from before
 *     the last progress message was drawn.  That is the "MixSplash freezes during the
 *     dashboard load".
 *
 * Both are the same mistake -- handing over at the wrong end of the gap -- and the fix
 * is to hand over at the far end instead.  The splash keeps animating, keeps holding
 * the console, and is dismissed from the first paintEvent, when there is finally
 * something else on the panel to look at.
 *
 * THE FLAG BEFORE THE QUIT, because mixos-splash-tick is still feeding the splash a
 * seconds count and stops only when it finds the flag.  Reversed, its next line would
 * land after the last thing the dashboard said.
 *
 * QUIT OR ABORT, and the caller has to say which, because the two words differ in
 * what mixsplash leaves the console in and both answers are wanted here.  /init told
 * it `handover' before switch_root, and `quit' honours that: it exits without
 * touching the mode, which is exactly right coming out of the first paint, where
 * this program has just taken KD_GRAPHICS for itself and a KD_TEXT from a dying
 * splash would blank the frame it is standing on.  `abort' means "give the text
 * console back whatever you were told earlier", which is what every path out of
 * textMode() wants: the mode is restored by mixsplash on its own way out, so the
 * KDSETMODE below is a second opinion rather than the only one, and it cannot lose
 * the race with the once-a-second re-take.
 *
 * SAFE FROM A SIGNAL HANDLER, which is not incidental: textMode() below calls this,
 * and textMode() runs from onFatal and onStall.  open, write and close are all
 * async-signal-safe, the guard is a sig_atomic_t, and there is no allocation and no
 * Qt anywhere in it.  O_NONBLOCK so that a channel that happens to be a FIFO with
 * nothing reading it fails the open instead of blocking a dying process forever; on
 * the regular file /init actually creates it means nothing and costs nothing.
 */
volatile sig_atomic_t g_splashDismissed = 0;

void dismissSplash(int giveBackTheConsole)
{
    static const char channel[] = "/dev/.mixsplash";
    static const char doneFlag[] = "/dev/.mixsplash-done";
    static const char handOver[] = "progress:100\nquit\n";
    static const char giveBack[] = "progress:100\nabort\n";
    const char *message = giveBackTheConsole ? giveBack : handOver;
    size_t length = giveBackTheConsole ? sizeof(giveBack) - 1 : sizeof(handOver) - 1;
    int fd;

    if (g_splashDismissed)
        return;
    g_splashDismissed = 1;

    fd = ::open(doneFlag, O_WRONLY | O_CREAT | O_CLOEXEC, 0644);
    if (fd >= 0)
        ::close(fd);

    fd = ::open(channel, O_WRONLY | O_APPEND | O_NONBLOCK | O_CLOEXEC);
    if (fd >= 0) {
        ssize_t written = ::write(fd, message, length);
        (void)written;
        ::close(fd);
    }
}

/*
 * THE SPLASH GOES FIRST, and that ordering is the whole of why this function is not
 * two lines any more.  Every caller is on the way out and wants the console back so
 * that what it prints next is readable -- but mixsplash re-takes KD_GRAPHICS once a
 * second, so a KDSETMODE with the splash still alive is undone inside a second and
 * the crash report is written to a console nothing is drawing.
 *
 * And Console::text() is unconditional, where the ioctl it replaced used to be
 * guarded by `if this process set the mode'.  That guard was for the case where Qt's
 * plugin set it rather than this file, on the grounds that undoing it was Qt's
 * business -- true while the program is running, and irrelevant here, because every
 * path into this function ends in _exit, abort or a re-raised fatal signal and Qt is
 * never going to get the chance.  It also missed the case that matters most: a
 * dashboard that dies BEFORE its first paint never owned the mode at all, the splash
 * did, and leaving the panel in KD_GRAPHICS with the splash gone is a black screen
 * with the reason for it invisible behind it.
 *
 * IT ALSO PUTS THE STREAM BACK, which is the half that is easy to forget.  From the
 * first paint this program's stdout and stderr are a file on a tmpfs; every line
 * below every caller of this function is a failure report, and a failure report that
 * goes to that file instead of to the panel is a failure report nobody will read.
 * Console::text() restores the two descriptors before it touches the mode.
 */
void textMode(void)
{
    dismissSplash(1);
    Console::text();
}

/* The step, when there is one, printed as ` step "..."' and as nothing at all when
 * the phase has not entered one.  Both strings are literals, so a handler reading
 * them cannot see a pointer half-written. */
void writeWhere(void)
{
    Trace::writeAll(2, "phase \"");
    Trace::writeAll(2, Trace::current());
    Trace::writeAll(2, "\"");
    if (Trace::currentStep()[0] != '\0') {
        Trace::writeAll(2, ", step \"");
        Trace::writeAll(2, Trace::currentStep());
        Trace::writeAll(2, "\"");
    }
}

void onStall(int)
{
    /* KD_TEXT FIRST.  Everything below it is written to a console that is not being
     * drawn until this ioctl lands. */
    textMode();
    Trace::writeAll(2, "\nmixdash: WATCHDOG -- ");
    writeWhere();
    Trace::writeAll(2, " did not finish.  Exiting so the console comes back.\n");
    writeBuild();
    /* Where it is stuck, which for a stall is the entire question. */
    Trace::backtraceTo(2);
    ::_exit(3);
}

void onFatal(int sig)
{
    textMode();
    if (!g_reported) {
        g_reported = 1;
        Trace::writeAll(2, "\nmixdash: died in ");
        writeWhere();
        Trace::writeAll(2, "\n");
        writeBuild();
        Trace::backtraceTo(2);
    }
    /* Re-raised with the default disposition so the kernel still reports the fault
     * and the exit status still says what happened.  systemd's Restart=on-failure
     * reads that status. */
    ::signal(sig, SIG_DFL);
    ::raise(sig);
}

/*
 * An exception that no handler matched.  The C++ runtime's own handler prints the
 * exception's TYPE and then aborts, which is worth keeping, so this prints what the
 * runtime cannot -- where the program was -- and then chains to it.
 *
 * This is not the same report as the catch at the bottom of main().  A handler runs
 * after unwinding, so it can say what was thrown and where the program had got to,
 * but the frames that threw are gone by then.  __cxa_throw in alloc.cpp is what
 * catches those, before any unwinding happens, on whichever thread it happened.
 */
std::terminate_handler g_prevTerminate = NULL;

void onTerminate(void)
{
    textMode();
    ::alarm(0);
    if (!g_reported) {
        g_reported = 1;
        Trace::writeAll(2, "\nmixdash: an exception nobody caught, in ");
        writeWhere();
        Trace::writeAll(2, "\n");
        writeBuild();
    }
    if (g_prevTerminate != NULL)
        g_prevTerminate();
    ::abort();
}

void onTerm(int)
{
    textMode();
    Trace::writeAll(2, "\nmixdash: asked to stop; console back in text mode\n");
    ::_exit(0);
}

/*
 * WHICH BUILD IS ON THE GLASS.  This board is updated across two partitions by two
 * different means: the boot image -- kernel, initramfs, /init -- is dragged onto the
 * vfat BOOT partition, which is the only one a Mac can write, while this binary lives
 * under /opt/mixos on an ext2 partition that a Mac cannot even mount and gets there
 * either baked into the image or unpacked from sd-root.tar.gz by /init.  Either half
 * can therefore be a version behind the other with nothing to show it, and an old
 * dashboard failing in an old way is indistinguishable from a new one failing -- which
 * is exactly the hour that was lost to a boot whose artifacts predated the fix.
 *
 * So /init passes on the id the boot image was built with and this says whether the
 * binary agrees.  Both ids are the first twelve characters of a sha256 over the
 * dashboard's own sources, so "they agree" means the two halves came out of one build.
 */
void announceBuild(void)
{
    const QByteArray expect = qgetenv("MIXDASH_EXPECT");

    /* Kept for the failure paths, which cannot go back to the environment safely. */
    ::strncpy(g_expect, expect.constData(), sizeof(g_expect) - 1);

    ::printf("mixdash: build %s\n", MIXDASH_BUILD_ID);
    if (expect.isEmpty()) {
        ::printf("mixdash: nothing said which build was expected -- either this was run "
                 "from a shell, or the boot image predates the check\n");
        return;
    }
    if (expect == MIXDASH_BUILD_ID) {
        ::printf("mixdash: the boot image expected %s, so both halves are this build\n",
                 expect.constData());
        return;
    }

    ::printf("mixdash: MISMATCH -- the boot image expected %s, this binary is %s.\n",
             expect.constData(), MIXDASH_BUILD_ID);
    ::printf("mixdash: one half of the card was not updated.  If the boot image is the\n"
             "         newer one, sd-root.tar.gz never unpacked onto the OS partition --\n"
             "         look further up for /init's \"stage:\" lines.  If this binary is\n"
             "         the newer one, the boot image on BOOT is stale: copy sd-boot/ over\n"
             "         again.  Whatever the trace below says, it is not about the sources\n"
             "         you last changed.\n");
}

/*
 * --probe runs before QApplication on purpose.  If the platform plugin is missing
 * or the framebuffer is not what the device tree said, this still answers, and its
 * answer is the first thing worth having from a boot that drew nothing.
 */
int probe(void)
{
    const int fd = ::open("/dev/fb0", O_RDONLY);
    if (fd < 0) {
        ::printf("mixdash: /dev/fb0 cannot be opened (%s)\n", ::strerror(errno));
        ::printf("mixdash: FB_SIMPLE should have bound the device tree's "
                 "simple-framebuffer node -- check dmesg for simple-framebuffer\n");
        return 1;
    }

    struct fb_var_screeninfo var;
    struct fb_fix_screeninfo fix;
    ::memset(&var, 0, sizeof(var));
    ::memset(&fix, 0, sizeof(fix));
    if (::ioctl(fd, FBIOGET_VSCREENINFO, &var) < 0
        || ::ioctl(fd, FBIOGET_FSCREENINFO, &fix) < 0) {
        ::printf("mixdash: /dev/fb0 opened but answered no geometry (%s)\n", ::strerror(errno));
        ::close(fd);
        return 1;
    }

    ::printf("mixdash: /dev/fb0 is \"%s\", %ux%u, %u bpp, stride %u, %u bytes mapped\n",
             fix.id, var.xres, var.yres, var.bits_per_pixel, fix.line_length, fix.smem_len);
    ::printf("mixdash: channels r%u@%u g%u@%u b%u@%u a%u@%u\n",
             var.red.length, var.red.offset, var.green.length, var.green.offset,
             var.blue.length, var.blue.offset, var.transp.length, var.transp.offset);

    /*
     * 32 bits per pixel is what the device tree's `x8r8g8b8' promises and what Qt's
     * raster engine can blit into without a conversion pass.  16 would still work
     * and would still be worth saying out loud.
     */
    if (var.bits_per_pixel != 32 && var.bits_per_pixel != 16)
        ::printf("mixdash: %u bpp is neither 16 nor 32; linuxfb will refuse it\n",
                 var.bits_per_pixel);

    ::close(fd);
    return 0;
}

/*
 * One font, found rather than assumed.  The payload's own copy comes first so the
 * dashboard looks the same on a card whose rootfs has no fonts at all; the rootfs
 * copies are the fallback, and if neither is there Qt falls back to whatever
 * fontconfig can find and the dashboard still draws.
 */
/* The first of these that exists and can be opened, or nothing.  loadFont() below
 * does the same walk for the same reason -- the payload first, the tree it was
 * built in second -- and this is the one-file version of it. */
QString firstReadable(const QStringList &paths)
{
    for (const QString &p : paths)
        if (QFileInfo(p).isReadable())
            return p;
    return QString();
}

QString loadFont()
{
    QStringList files;
    const QDir payload("/opt/mixos/qt/fonts");
    if (payload.exists())
        for (const QString &f : payload.entryList(QStringList() << "*.ttf", QDir::Files, QDir::Name))
            files << payload.filePath(f);
    files << "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
          << "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
          << "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
          << "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf";

    QString family;
    for (const QString &f : files) {
        if (!QFileInfo::exists(f))
            continue;
        const int id = QFontDatabase::addApplicationFont(f);
        if (id < 0)
            continue;
        const QStringList families = QFontDatabase::applicationFontFamilies(id);
        if (families.isEmpty())
            continue;
        /*
         * EVERY face is registered -- the Terminal asks QFontDatabase for "DejaVu
         * Sans Mono" by name and cannot draw a character grid without it -- but the
         * MONO one is never chosen as the application-wide font.  The payload
         * directory is read in name order, and one day a file that sorts before
         * DejaVuSans.ttf will be added to it; when that happens this dashboard
         * should not silently turn monospace.
         */
        if (family.isEmpty() && !families.first().contains(QLatin1String("Mono")))
            family = families.first();
    }
    return family;
}

/*
 * The platform spec, defaulted rather than demanded.  An explicit QT_QPA_PLATFORM
 * still wins -- that is how this binary runs under X or Wayland on a development
 * machine -- but `linuxfb' on its own is completed to
 * `linuxfb:nographicsmodeswitch', because the unit file that names it lives on the
 * BOOT partition and this binary lives on the OS partition, and the two are updated
 * by different means.  A card whose /init predates the option would otherwise put
 * the console back in KD_GRAPHICS at plugin init and take the panel with it.
 */
void defaultPlatform(void)
{
    QByteArray spec = qgetenv("QT_QPA_PLATFORM");
    if (spec.isEmpty())
        spec = "linuxfb";
    if (!spec.startsWith("linuxfb"))
        return;
    if (!spec.contains("graphicsmodeswitch"))
        spec += ":nographicsmodeswitch";
    qputenv("QT_QPA_PLATFORM", spec);
}

/*
 * QStandardPaths warns about XDG_RUNTIME_DIR before anything else this program does,
 * and it is right to: Qt puts its own sockets and lock files there.  systemd's
 * RuntimeDirectory= makes this directory, but the dashboard has to be runnable from a
 * shell too, so it is made here when nobody has made it.
 */
void defaultRuntimeDir(void)
{
    if (qEnvironmentVariableIsSet("XDG_RUNTIME_DIR"))
        return;
    if (::mkdir("/run/mixdash", 0700) == 0 || errno == EEXIST)
        qputenv("XDG_RUNTIME_DIR", "/run/mixdash");
}

} /* namespace */

int main(int argc, char **argv)
{
    bool once = false;
    bool windowed = false;
    bool qtInput = false;

    Trace::begin();
    /*
     * Line-buffered, and this is not cosmetic.  stdout under systemd is a pipe to the
     * journal, so libc block-buffers it: a checkpoint printed just before a hang sits
     * in a 4 KB buffer and is never seen, which is precisely what happened to the one
     * line this program used to print.  stderr is unbuffered already, which is the
     * only reason the QStandardPaths warning made it onto the glass.
     */
    ::setvbuf(stdout, NULL, _IOLBF, 0);

    for (int i = 1; i < argc; ++i) {
        const char *a = argv[i];
        if (!::strcmp(a, "--probe")) {
            announceBuild();
            return probe();
        }
        if (!::strcmp(a, "--once"))
            once = true;
        else if (!::strcmp(a, "--windowed"))
            windowed = true;
        else if (!::strcmp(a, "--qt-input"))
            qtInput = true;
        else if (!::strcmp(a, "--help") || !::strcmp(a, "-h")) {
            ::printf("mixdash -- the MixOS dashboard\n"
                     "  --probe      report /dev/fb0's geometry and exit\n"
                     "  --once       draw one screen, wait three seconds, exit 0\n"
                     "  --windowed   do not go fullscreen (for a development machine)\n"
                     "  --qt-input   let Qt read evdev instead of the built-in map\n"
                     "\n"
                     "MIXDASH_DEADLINE=<s>  watchdog per startup phase (0 off, 90 default)\n"
                     "MIXDASH_EXPECT=<id>   build the boot image expects; /init sets it\n"
                     "\n"
                     "This is build " MIXDASH_BUILD_ID ".\n");
            return 0;
        }
    }

    if (qEnvironmentVariableIsSet("MIXDASH_DEADLINE"))
        Trace::setDeadline(qEnvironmentVariableIntValue("MIXDASH_DEADLINE"));

    /*
     * First, before the tty and before Qt.  If the two halves of the card disagree then
     * nothing below is evidence about the sources anybody last edited, and that has to
     * be the first line read rather than something inferred from the last.
     */
    announceBuild();

    /*
     * The tty before the framebuffer, and both before Qt.  O_RDWR because KDSETMODE
     * needs it; failure is not fatal and not even unusual -- run from ssh there is no
     * /dev/tty0 to open -- but on this board it is the console, and a dashboard that
     * cannot put it back into text mode is a dashboard that can silence the machine.
     */
    if (!Console::open())
        ::printf("mixdash: /dev/tty0 will not open (%s); the console mode is not ours\n",
                 ::strerror(errno));

    ::signal(SIGALRM, onStall);
    ::signal(SIGTERM, onTerm);
    ::signal(SIGINT, onTerm);
    ::signal(SIGHUP, onTerm);
    ::signal(SIGSEGV, onFatal);
    ::signal(SIGABRT, onFatal);
    ::signal(SIGBUS, onFatal);
    ::signal(SIGFPE, onFatal);
    ::signal(SIGILL, onFatal);
    ::atexit(textMode);
    /* Chained rather than replaced: the runtime's own handler is what prints the
     * exception's type, and it is the reason `bad_alloc' was ever a word on this
     * panel.  onTerminate adds the phase, the step and the build in front of it. */
    g_prevTerminate = std::set_terminate(onTerminate);

    /*
     * The framebuffer's own answer, every boot and not just under --probe.  Six lines,
     * and they are the six that decide whether anything after them can possibly draw.
     */
    Trace::phase("framebuffer");
    (void)probe();

    /*
     * Set before QApplication, because the platform plugin reads its environment
     * while it is being constructed.
     */
    defaultPlatform();
    defaultRuntimeDir();
    if (!qtInput && !qEnvironmentVariableIsSet("QT_QPA_FB_DISABLE_INPUT"))
        qputenv("QT_QPA_FB_DISABLE_INPUT", "1");
    ::printf("mixdash: QT_QPA_PLATFORM=%s\n", qgetenv("QT_QPA_PLATFORM").constData());

    Trace::phase("QApplication -- loads the platform plugin and opens /dev/fb0");
    QApplication app(argc, argv);
    app.setApplicationName("mixdash");
    app.setApplicationDisplayName("MixOS");
    app.setOverrideCursor(Qt::BlankCursor);

    /*
     * The platform and the geometry, HERE, and not at the end of startup where this
     * line used to be.  It is the answer to "did linuxfb bind", and a phase after it
     * that never returns must not be allowed to take the answer with it.
     */
    const QScreen *screen = QApplication::primaryScreen();
    ::printf("mixdash: %s on %s, %dx%d\n",
             QT_VERSION_STR,
             qPrintable(QApplication::platformName()),
             screen ? screen->geometry().width() : 0,
             screen ? screen->geometry().height() : 0);

    /*
     * Its own phase because it is the first plausible suspect for a startup that
     * reaches no frame: Qt5 on Debian links libfontconfig into QtGui, so this is
     * where fontconfig builds its cache if the rootfs has none -- a whole-system font
     * scan, on a 1.7 GHz A7, off an SD card.  QT_QPA_FONTDIR does not prevent it;
     * only QBasicFontDatabase reads that variable, and this build has fontconfig.
     */
    Trace::phase("fonts -- QFontDatabase, and fontconfig behind it");
    const QString family = loadFont();
    ::printf("mixdash: font \"%s\"\n",
             family.isEmpty() ? "fontconfig default" : qPrintable(family));
    QFont f = family.isEmpty() ? app.font() : QFont(family);
    f.setPixelSize(13);
    app.setFont(f);

    /*
     * The strings database, before anything builds a string.
     *
     * After the font and before the try block on purpose.  It has to be after
     * QApplication exists, because it installs a translator on qApp; it has to be
     * before the Dashboard constructor, because every page title and every card
     * name is built in there and a translator installed afterwards would leave the
     * shell in English until each page was walked into.  And it is outside the try
     * because it cannot throw anything interesting -- the table is in .rodata and
     * there is nothing to open, which is the whole reason it is a table.
     */
    Trace::phase("strings -- the localisation table");
    Strings::install();

    /*
     * The time zone, in the same breath and for the same reason.
     *
     * The status bar starts telling the time a few milliseconds after the
     * Dashboard constructor returns, and on a device whose /etc could not be
     * written -- /init mounts the OS partition read-only on some of its recovery
     * paths -- the only record of where the user said they are is the settings
     * file.  This sets TZ on mixdash alone from that record: it writes nothing,
     * needs no privilege, and is a no-op on a device that was never taken to the
     * Region page.  See RegionPage::applyStoredTimezone().
     */
    RegionPage::applyStoredTimezone();

    /*
     * WHY THE REST OF main() IS INSIDE A try.  An exception that reaches the top of
     * main is std::terminate, which is abort(), which is SIGABRT -- and what the
     * console then showed was the two lines the runtime prints ("terminate called
     * after throwing an instance of 'std::bad_alloc'") followed by onFatal's phase.
     * That is a fault report with no fault in it: bad_alloc carries no size and
     * what() is a fixed string.  alloc.cpp now prints the size and the stack at the
     * throw site, where the information still exists, and this catch is the other
     * end of it -- it turns an abort into an orderly exit that names the step, puts
     * the console back into text mode through the normal path, and leaves every line
     * above readable instead of scrolled away by a restart.
     *
     * Exit 4, and it is in the unit's RestartPreventExitStatus with 3 for the same
     * reason the watchdog's is: a startup that failed deterministically will fail
     * the same way three more times and scroll its own explanation off the glass.
     */
    int rc = 0;
    try {
        /*
         * Its own phase because it is the first plausible suspect for a startup that
         * reaches no frame -- and its own STEPS, because "the constructor" is eleven
         * objects and the first crash here named all of them at once.  One of those
         * steps puts a QFileSystemModel on /run/j36/card, a read-only mount of a
         * partition on the same SD card this program was loaded from.
         */
        /*
         * Before the Dashboard rather than inside it: the constructor's buildPages()
         * lays the card grid out once, and a volume list that starts empty and fills
         * in a moment later would show the grid rebuilding itself on the first frame
         * for anyone who booted with a stick already in the port.  start() only reads
         * the automounter's state files and opens one fd, so it is cheap enough to do
         * before there is anything to draw.
         */
        Trace::phase("Volumes -- what the automounter has already mounted");
        Volumes::instance().start();

        Trace::phase("Dashboard -- the pages, the dock and the evdev map");
        Dashboard dash;

        /*
         * The console stops being drawn on when the dashboard first paints, and not
         * one moment sooner.  Failing before this point leaves every line above on
         * the glass.
         */
        QObject::connect(&dash, &Dashboard::firstPainted, &dash, [&dash]() {
            Trace::phase("first paint -- the console is now KD_GRAPHICS");
            /*
             * The mode before the splash, so there is never an instant with neither
             * of them holding it: dismissSplash() is what stops mixsplash re-taking
             * KD_GRAPHICS every second, and between that stopping and this ioctl
             * landing the console would be free for the next thing that resets it.
             */
            Console::take();
            dismissSplash(0);
            /*
             * AND THE STREAM COMES OFF THE PANEL HERE TOO.  Up to this line stdout
             * and stderr are the best thing the glass can show and the unit sends
             * them to the console on purpose.  Past it they are the worst: a Qt
             * warning, or the first line of a child that forgot to capture its
             * output, is text drawn straight over the dashboard by a channel no
             * amount of holding the VT mode can close, because the text is this
             * program's own.  console.h has the rest of the argument; textMode()
             * puts both descriptors back before any failure report is written.
             */
            Console::toLog(kLogPath);
            /*
             * AND THEN PAINT IT ALL AGAIN, once, a quarter of a second later.  The
             * splash draws at 25 fps and reads its channel between frames, so it can
             * put one more frame onto the panel after this one -- and Qt would not
             * notice, because linuxfb only flushes what a widget has marked dirty and
             * nothing here is dirty any more.  The result would be a splash frame
             * sitting on top of the dashboard until something happened to be
             * redrawn.  One unconditional full repaint after mixsplash has certainly
             * gone costs a frame nobody sees in the normal case and closes that.
             */
            QTimer::singleShot(250, &dash, [&dash]() { dash.update(); });

            /*
             * THE GUARD, and it is the same lesson as the line above generalised.
             *
             * KD_GRAPHICS is a mode and not a lock: agetty, systemd-vconsole-setup
             * and systemd's own console logging each clear it, and this unit is
             * StandardOutput=journal+console, so STARTING ANY UNIT from a page can
             * be what does it.  That is what "changing the sharing settings puts a
             * console with a few kernel lines on it over the dashboard" was, and
             * mixsplash met the same thing first -- console_hold() in mixsplash.c
             * has the list of suspects and the same answer.
             *
             * The splash could stop at re-taking the mode because it redraws every
             * frame anyway.  This program does not, so the two halves are here: hold
             * whenever it is not ours, and REPAINT THE WHOLE WINDOW when it turns
             * out not to have been.  update() and not repaint(), because this runs
             * on the event loop and a full synchronous paint from a timer would be
             * one frame's worth of jitter for nothing.
             *
             * Once a second, which is mixsplash's interval and is chosen the same
             * way: it costs one ioctl that reads a flag, and the window it leaves is
             * one second of text on the panel in the rare case rather than text that
             * stays until something else happens to be redrawn.  A page that blocks
             * its own event loop waiting for a child gets no ticks at all while it
             * waits, which is why Console::hold() is public and why SharingPage's
             * shell-outs call it themselves between slices.
             */
            QTimer *guard = new QTimer(&dash);
            guard->setInterval(1000);
            QObject::connect(guard, &QTimer::timeout, &dash, [&dash]() {
                if (Console::hold())
                    dash.update();
            });
            guard->start();

            /*
             * ── AND THE NOISE THE THING MAKES WHEN IT IS READY ──
             *
             * Here and not one line earlier: this runs from the first paint, so
             * the chime starts at the moment the dashboard is actually on the
             * glass rather than at the moment this program decided it would be.
             * Detached, so nothing about it can delay the line below.
             *
             * The payload path first and the source tree second, which is the
             * order every other asset in this program is looked for in -- see the
             * font search in main() -- so a development run out of the build
             * directory finds the file it was just built next to.
             */
            MediaPage::playOnce(firstReadable(QStringList()
                                              << "/opt/mixos/share/mixdash/startup.mp3"
                                              << QCoreApplication::applicationDirPath()
                                                     + "/startup.mp3"
                                              << QCoreApplication::applicationDirPath()
                                                     + "/../resources/startup.mp3"));

            /* Startup is over; a deadline from here would kill a working dashboard. */
            ::alarm(0);
            ::signal(SIGALRM, SIG_DFL);
        });

        Trace::phase("show -- fullscreen, and then the first frame");
        if (windowed) {
            dash.resize(640, 480);
            dash.show();
        } else {
            dash.showFullScreen();
        }

        if (once)
            QTimer::singleShot(3000, &app, []() { QApplication::quit(); });

        rc = app.exec();
    } catch (const std::exception &e) {
        /* KD_TEXT before anything is written, exactly as the signal handlers do it:
         * a console still in KD_GRAPHICS is a console fbcon is not drawing. */
        textMode();
        ::alarm(0);
        g_reported = 1;
        Trace::writeAll(2, "\nmixdash: threw ");
        Trace::writeAll(2, e.what());
        Trace::writeAll(2, " in ");
        writeWhere();
        Trace::writeAll(2, "\n");
        writeBuild();
        /* No backtrace here on purpose: the stack was unwound to reach this handler,
         * so the frames that threw are already gone.  The THROW report that
         * alloc.cpp's __cxa_throw printed further up is where they are. */
        return 4;
    } catch (...) {
        textMode();
        ::alarm(0);
        g_reported = 1;
        Trace::writeAll(2, "\nmixdash: threw something that is not a std::exception in ");
        writeWhere();
        Trace::writeAll(2, "\n");
        writeBuild();
        return 4;
    }

    Trace::phase("exit");
    textMode();
    return rc;
}
